export const DRUGS_MASTER = [
  { id: 1, name: "Zolpidem", category: "Sedative" },
  { id: 2, name: "Alprazolam", category: "Anxiolytic" },
  { id: 3, name: "Morphine Sulfate", category: "Opioid" },
  { id: 4, name: "Diazepam", category: "Benzodiazepine" },
  { id: 5, name: "Oxycodone", category: "Opioid" },
  { id: 6, name: "Fentanyl Citrate", category: "Opioid" },
  { id: 7, name: "Lorazepam", category: "Benzodiazepine" },
  { id: 8, name: "Methadone", category: "Opioid" },
  { id: 9, name: "Buprenorphine", category: "Opioid" },
  { id: 10, name: "Tramadol", category: "Opioid" },
  { id: 11, name: "Codeine Phosphate", category: "Opioid" },
  { id: 12, name: "Hydrocodone", category: "Opioid" },
  { id: 13, name: "Ketamine", category: "Anesthetic" },
  { id: 14, name: "Midazolam", category: "Benzodiazepine" },
  { id: 15, name: "Nitrazepam", category: "Sedative" },
  { id: 16, name: "Temazepam", category: "Sedative" },
  { id: 17, name: "Phenobarbital", category: "Barbiturate" },
  { id: 18, name: "Secobarbital", category: "Barbiturate" },
  { id: 19, name: "Pentobarbital", category: "Barbiturate" },
  { id: 20, name: "Clonazepam", category: "Benzodiazepine" },
];
