import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf8ff",
        foreground: "#1b1b23",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3effb",
        "inverse-primary": "#c2c1ff",
        "inverse-surface": "#302f38",
        "on-background": "#1b1b23",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#8c8bff",
        "on-primary-fixed": "#0c006a",
        "on-primary-fixed-variant": "#352fb7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4f4f82",
        "on-secondary-fixed": "#161546",
        "on-secondary-fixed-variant": "#424174",
        "on-surface": "#1b1b23",
        "on-surface-variant": "#464554",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f27059",
        "on-tertiary-fixed": "#3f0300",
        "on-tertiary-fixed-variant": "#862112",
        "outline": "#777585",
        "outline-variant": "#c7c4d6",
        "primary": "#0c0069",
        "primary-container": "#1a05a2",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c2c1ff",
        "secondary": "#59598d",
        "secondary-container": "#c5c4ff",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c2c1fc",
        "surface": "#fcf8ff",
        "surface-bright": "#fcf8ff",
        "surface-container": "#f0ecf8",
        "surface-container-high": "#eae6f2",
        "surface-container-highest": "#e4e1ec",
        "surface-container-low": "#f5f2fe",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd8e4",
        "surface-tint": "#4e4bcf",
        "surface-variant": "#e4e1ec",
        "tertiary": "#3e0300",
        "tertiary-container": "#650700",
        "tertiary-fixed": "#ffdad4",
        "tertiary-fixed-dim": "#ffb4a6"
      },
    },
  },
  plugins: [],
};
export default config;
